### ISSUE TITLE
Test code for data without label

### ISSUE THREAD

**Issue by jianjun0407** [BAAI-DCAI/SegVol#11]
Tried the web version of the test you provided（https://huggingface.co/spaces/BAAI/SegVol）, can support test data without label. 
But the inferce_demo.py test code on github can only test data with labels. Could you expose the test code of the data without label and test it by the user entering the prompt point coordinates? 
In other words, can the test code called by the web version be exposed? Looking forward to your reply!

**Comment by Yuxin-Du-Lab** [comment]
Actually the web demo code is also open-source. You can see the code in the SegVol space/Files tag and clone it from here (note that the web demo code is run on CPU):

![20240109094103](https://github.com/BAAI-DCAI/SegVol/assets/60123629/1a130f2f-5867-4970-890e-5245cd80878f)
