### ISSUE TITLE
There's an error during execution, please advise on how to adjust and correct it.

### ISSUE THREAD

**Issue by wliu0218** [BAAI-DCAI/SegVol#12]
Executing bash script/inference_demo.sh in Ubuntu results in an error.

![image](https://github.com/BAAI-DCAI/SegVol/assets/63486244/d7abf6e9-28b1-43c3-9819-d90fd016c6e7)

**Comment by Yuxin-Du-Lab** [comment]
Could you please provide more information about your demo case? Is it a DICOM file/dir?

**Comment by wliu0218** [comment]
![image](https://github.com/BAAI-DCAI/SegVol/assets/63486244/33c5a411-5110-4f84-aff2-60a0af26feb0)
The data path setting is as shown in the diagram, does running the demo involve placing CT scans in the CT folder and annotations in the GT folder? Do the files stored in the CT and GT folders have to be in DICOM format? My data is in NII format.
Also, I would like to ask, can the SegVol model directly delineate lesions through the inference method without specifying box and text prompt? thanks.

**Comment by Yuxin-Du-Lab** [comment]
I know what is the problem. 
The ct_path and gt_path should be set as the path of nii.gz file. For example, if your ct case is in the path of /home/xxx/yyy.nii.gz . You need to set the ct_path as ' /home/xxx/yyy.nii.gz' to navigate to the file. Just do the same thing for gt_path.

For the second question, SegVol need at least one type of prompts(point, box or text) to drive model.

**Comment by wliu0218** [comment]
The problem has been solved, thanks
