### ISSUE TITLE
Can it be deployed locally?

### ISSUE THREAD

**Issue by wliu0218** [BAAI-DCAI/SegVol#14]
I have already cloned the program from the website as shown in the picture below. Can I deploy it locally? If so, is there a guide and process for it?

**Comment by Yuxin-Du-Lab** [comment]
Sure. You can deploy it locally and run it on your CPU. You need to follow the tutorial of **streamlit** and install the conda environment based on the [requirements file](https://huggingface.co/spaces/BAAI/SegVol/blob/main/requirements.txt).

**Comment by wliu0218** [comment]
Hello,  when  running  app.py with  administrator  privileges  in  Windows command line,  an  error  occurs  when  clicking  the  run  command  button.
![image](https://github.com/BAAI-DCAI/SegVol/assets/63486244/333ca854-4c89-4d3e-af1f-802e04b39b36)

**Comment by Yuxin-Du-Lab** [comment]
You can disable the following code for download function in app.py and try again:
```python
with tempfile.NamedTemporaryFile(suffix=".nii.gz") as tmpfile:
            nib.save(img_nii, tmpfile.name)
            with open(tmpfile.name, "rb") as f:
                bytes_data = f.read()
                st.download_button(
                    label="Download result(.nii.gz)",
                    data=bytes_data,
                    file_name="segvol_preds.nii.gz",
                    mime="application/octet-stream",
                    disabled=img_nii is None
                )
```

**Comment by wliu0218** [comment]
Hello,  the  program  can  run  after  removing  this  part  of  the  code.  After  removing  the  code,  will  it  affect  the  preservation  of  the  ROI  area  marked,  now，the  downloaded  charts  cannot  be  clicked.  If  there  is  no  impact,  how  can  ROI  be  saved?
![Uploading image.png…]()
