### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/SegVol-main/get_process_data/0000/0000.json'

### ISSUE THREAD

**Issue by zwhyyyy** [BAAI-DCAI/SegVol#15]
I followed the official documentation but this error occurred in the process of training.

**Comment by Yuxin-Du-Lab** [comment]
Please recheck whether [this function](https://github.com/BAAI-DCAI/SegVol/blob/7f615d7e45b07a17cc2f8dc14f22bef1d6db1b49/data_process/train_data_process.py#L172) conducts well
