### ISSUE TITLE
about FH Algorithm？

### ISSUE THREAD

**Issue by gaoqiong123** [BAAI-DCAI/SegVol#17]
In your paper, you mentioned the implementation of the FH algorithm for generating pseudo-labels. Could you please provide more details on how it was implemented?

**Comment by lzy886** [comment]
Same issue. I'm also looking for supplementary material.

**Comment by Yuxin-Du-Lab** [comment]
Our FH algorithm code has been public [here](https://github.com/BAAI-DCAI/SegVol/blob/main/data_process/felzenszwalb.py).

In detail, we add the z-axis to the original FH algorithm and configure the hyperparameter for the foreground normalized CT scans. The modified FH algorithm can generate relatively reliable panoramic masks for CT scans.
