### ISSUE TITLE
How many GPUs were used to run the train experiment?

### ISSUE THREAD

**Issue by ArmandAlbert** [BAAI-DCAI/SegVol#2]
Hello, I think you did a good job. I want to reproduce the training process myself. May I ask how many GPUs were used to run the experiment?

**Comment by Yuxin-Du-Lab** [comment]
Thanks for your attention! We trained SegVol on 8x A100(40G) GPUs for about 30 days.

**Comment by H47sj** [comment]
> Thanks for your attention! We trained SegVol on 8x A100(40G) GPUs for about 30 days. Additionally, we believe it is trainable on single GPU if the image encoder and text encoder are freezed and the well-trained params are loaded.

Hi, @Yuxin-Du-Lab, may I ask whether the 30 days is the time for ViT's pre-train + SegVol's fine-tune or just only the latter? And how many GPUs and how long does ViT's pre-train take?
