### ISSUE TITLE
pretraining 96k CT scan

### ISSUE THREAD

**Issue by winwinJJiang** [BAAI-DCAI/SegVol#24]
Hi, 

How did you end up with pretrain your 96k CT scan for 2000 epochs with only 8*40GB GPU?
How long it takes?

Our experience is that this is practically impossible. We have even more GPUs (32*80GB) but pretraining for 500 epoch has token 7 days.

Any idea or clarification?!?!?!?!?!!?

**Comment by Yuxin-Du-Lab** [comment]
Thanks for your inquiry. Your question has been answered in issue #25
