### ISSUE TITLE
About pre-trained ViT weight file

### ISSUE THREAD

**Issue by H47sj** [BAAI-DCAI/SegVol#26]
Hi, 
Thank you for your great job and sharing the models. 
Based on your paper's introduction:" ......to train the 3D ViT encoder of SegVol on the collected 96K CTs for 2000 epochs.......", I downloaded the weight file "ViT_pretrain.ckpt" in Google Drive.
But I found its epoch num is 399 instead of 2000. So, may I ask if you can share the 2000 epochs' weight file?
Thanks.

**Comment by baifanxxx** [comment]
Hi,

Now, the released weight is what we described in the paper. The 399 is not the overall epoch but the continual pre-trained epoch because we load the weights trained multiple times to continue the pre-training.

**Comment by H47sj** [comment]
> Hi,
> 
> Now, the released weight is what we described in the paper. The 399 is not the overall epoch but the continual pre-trained epoch because we load the weights trained multiple times to continue the pre-training.
Thanks for your reply. I understand.
