### ISSUE TITLE
DICOM FILE

### ISSUE THREAD

**Issue by JoshuaYang0926** [BAAI-DCAI/SegVol#3]
I encountered a problem when running the demo.... zzzz
 "File is missing DICOM File Meta Information header or the 'DICM' "
Traceback (most recent call last):
  File "inference_demo.py", line 221, in <module>
    main(args)
  File "inference_demo.py", line 208, in main
    data_item = process_ct_gt(ct_path, gt_path, categories, args.spatial_size)   # keys: image, label

    "File is missing DICOM File Meta Information header or the 'DICM' "
pydicom.errors.InvalidDicomError: File is missing DICOM File Meta Information header or the 'DICM' pre                      
 fix is missing from the header. Use force=True to force reading.

**Comment by JoshuaYang0926** [comment]
{
    "dataset_name": "AbdomenCT-1k",
    "categories": ["liver", "kidney", "spleen", "pancreas"],
    "demo_case": {
        "ct_path": "/home/SegVol-main/path/to/Case_image",
        "gt_path": "/home/SegVol-main/path/to/Case_label" 
    }
}
Thanks for your reply!Maybe I need to add the absolute path to the data? Like this
"/home/SegVol-main/path/to/Case_image/Case_image_00001_0000.nii.gz"

After setting it up like this, I encountered a data normalization problem. Is monai's data normalization only suitable for tensor data?
    ct_voxel_ndarray = ct_narray.copy()
AttributeError: 'MetaTensor' object has no attribute 'copy'

**Comment by Yuxin-Du-Lab** [comment]
'MetaTensor' is the special tensor type of MONAI. In SegVol code, we discard the meta_dict temporally in [ `ct_voxel_ndarray, _ = img_loader(case_path)`](https://github.com/BAAI-DCAI/SegVol/blob/03f26a3d66456c34dc0c196d3b83467d4496a00e/data_process/demo_data_process.py#L69). Maybe you have edited the transform pipeline?

**Comment by Yuxin-Du-Lab** [comment]
Firstly, the demo_case config is right if you set the right '/path/to' of image and label paths of nii.gz files. 

Then, `ct_voxel_ndarray, _ = img_loader(case_path)` seems behave different from our expection. I think you can modify the pipline based on your MONAI environment:
1. load the nii.gz file into memory 
2. extract its array and translate it into numpy array 
3. input the numpy array to the follow pipeline: [raw data here](https://github.com/BAAI-DCAI/SegVol/blob/03f26a3d66456c34dc0c196d3b83467d4496a00e/data_process/demo_data_process.py#L70) and [ground truth here](https://github.com/BAAI-DCAI/SegVol/blob/03f26a3d66456c34dc0c196d3b83467d4496a00e/data_process/demo_data_process.py#L77)

I think this is equivalent to the original code.

**Comment by JoshuaYang0926** [comment]
I solved the bugs that MONAI brought to me, and now the test demo can be used normally. The effect of organ segmentation is really good! Also, I would like to try out the effect of lesion segmentation and I would like to know how to use text prompt words, can you provide some suggestions？！ Thank you! 😄

**Comment by Yuxin-Du-Lab** [comment]
It's exciting to see that you can run the code!

For the text prompt group, you can edit it [here](https://github.com/BAAI-DCAI/SegVol/blob/d84814378fd5eb784e2b976a1429c0add68540be/config/config_demo.json#L3) for a new case in new dataset. Notice that the **order** of the categories should be corresponding to the Ground Truth index of the new dataset and please ignore the background category.

For a single text prompt, you can delete the [for loop](https://github.com/BAAI-DCAI/SegVol/blob/d84814378fd5eb784e2b976a1429c0add68540be/inference_demo.py#L52C6-L52C6) to just inference a specific category. At the same time, you should assign your text prompt word to [text_single](https://github.com/BAAI-DCAI/SegVol/blob/d84814378fd5eb784e2b976a1429c0add68540be/inference_demo.py#L61C11-L61C11). You can use 'lung tumor', 'colon cancer' or 'liver tumor' etc. as your lesion text prompt word.

Finally, I strongly recommend you to try the [web demo](https://huggingface.co/spaces/yuxindu/SegVol) first. You can just upload your case and try any possible prompt to play with SegVol.😋

**Comment by JoshuaYang0926** [comment]
I look forward to your follow-up work and thank you for helping me! 🥳

**Comment by JoshuaYang0926** [comment]
Looking forward to your follow-up work and thanks for your help! 🥳
