### ISSUE TITLE
Dimension of upload data？

### ISSUE THREAD

**Issue by flatblackwhite** [BAAI-DCAI/SegVol#6]
The results on Hugging Face are very cool. What are the dimensions of the data to be uploaded? I've tried uploading a few, but encountered some problems
<img width="974" alt="截屏2023-12-11 10 03 35" src="https://github.com/BAAI-DCAI/SegVol/assets/22386567/7072d095-7902-42f6-9880-9549bafcf871">

**Comment by Yuxin-Du-Lab** [comment]
Could you please provide more information about your cases and your prompts to help us localize the bug?

**Comment by flatblackwhite** [comment]
How can i send you my case? I can't find your email in segvol paper.

**Comment by Yuxin-Du-Lab** [comment]
You can send your case to my email: yuxindu444@gmail.com 😊

**Comment by Yuxin-Du-Lab** [comment]
I checked the code and found a bug in the positioning of the spatial prompt in our demo on Hugging Face. This was causing your BraTS case to report an out-of-bounds error. 
It has been fixed now. Thanks for your bug report!🤝
