### ISSUE TITLE
How to set the label of negative sample point？

### ISSUE THREAD

**Issue by jianjun0407** [BAAI-DCAI/SegVol#8]
Thank you for sharing. I have a question about the prompt, when the prompt is a point, there's no doubt that the label of the positive sample point is set to 1, so if it's a negative sample point, is its label set to -1, or is it set to 0？
![111](https://github.com/BAAI-DCAI/SegVol/assets/19251556/926044e9-d3ac-47ff-9cbe-5775531eddb9)
![222](https://github.com/BAAI-DCAI/SegVol/assets/19251556/1d56bb0e-9955-4c9c-8034-0ddc46851fd3)

**Comment by Yuxin-Du-Lab** [comment]
Point label 1 for positive points. 
Point label 0 for negative points. 
Point label -1 for ignored points.

Ignored points are used to fill the point prompt tensor into the same shape.

**Comment by jianjun126** [comment]
Thank you for your reply.
I also have a question is, when the current algorithm is testing the image, I see that the pre-processing stage does not carry out a unified spacing operation, is there no need to deal with it?
In other words, when you train the model, do you unify the spacing to a fixed value for data of different spacing?

**Comment by Yuxin-Du-Lab** [comment]
No need to deal with it. We did not conduct the unified spacing operation during training phase and inference phase. This is due to the data scalability considerations.
