### ISSUE TITLE
About the coordinate system （“RAS”）

### ISSUE THREAD

**Issue by jianjun0407** [BAAI-DCAI/SegVol#9]
If the ct_voxel_ndarray is  np.ndarray type and is assigned to item['image'], execute the command: Orientationd(keys=["image", "label"], axcodes="RAS"), can't pass in the original coordinate system information of the test image. Is there any problem here?

![1](https://github.com/BAAI-DCAI/SegVol/assets/19251556/e1392ef1-0e2b-4f87-bbf6-f8a1d9b3c683)
![2](https://github.com/BAAI-DCAI/SegVol/assets/19251556/a758feb7-30a8-415b-b2ce-1114819dda0b)

**Comment by Yuxin-Du-Lab** [comment]
I think it would be meaningless to apply RAS orientation on numpy image. If you want to keep the RAS orientation transform, I think you can compose the monai.transforms.LoadImage with the following transform operations.

**Comment by jianjun0407** [comment]
Thank you for your quick reply.
 Referring to the demonstration video you give, intuitively from the image, the final image of the incoming algorithm, cross-sectional view, is the bed board on the top; In the coronal view, the lungs are below and the abdomen is above. 
In other words, the image that the network is going to input is going to look like this. Am I right?
![3](https://github.com/BAAI-DCAI/SegVol/assets/19251556/5fc098d3-33b5-422d-8ba4-7d4751514e1c)

**Comment by Yuxin-Du-Lab** [comment]
hhh, I have to admit it looks strange. Actually you can input images with any orientation. We performed flip augmentation in training phase.😊

**Comment by jianjun0407** [comment]
That would be great！
